---
title: "Inductive multi-proxy analysis of Mesolithic population dynamics on the Norwegian Skagerrak coast"
author: 
- 'Isak Roalkvam'
- 'University of Oslo, Institute of Archaeology, Conservation and History'
  # - IsakRoalkvam:
  #     email: isak.roalkvam@iakh.uio.no
  #     institute: [iakh]
      # correspondence: true
#   - name: Steinar Solheim
#     email: steinar.solheim@khm.uio.no
#     institute: [mch]
#     correspondence: false
institute:
  - iakh: Institute of Archaeology, Conservation and History, University of Oslo
#   - mch: Museum of Cultural History, University of Oslo
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::pdf_document2:
      fig_caption: yes
      # toc: false
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
      pandoc_args:
      # - --lua-filter=../templates/scholarly-metadata.lua
      # - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  Text of abstract
keywords: |
  keyword 1; keyword 2; keyword 3
highlights: |
  These are the highlights. 
---

Keywords: `r rmarkdown::metadata$keywords`

Highlights: `r rmarkdown::metadata$highlights`


```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/",
  dpi = 300
)
```

# Introduction
Population size is regarded as one of the primary drivers of cultural variation and is therefore of critical importance to our understanding of past human societies [@shennan2000]. In recent years, frequency of radiocarbon dates have been used extensively as one proxy for relative population size [e.g. @french2021; @crema2022], including in Norwegian Stone Age archaeology [@solheim2018a; @solheim2020a; @nielsen2019; @nielsen2021; @bergsvik2021; @jorgensen2020; @lundstrom2021]. The potentially immense value of insights into past population dynamics, combined with the ubiquity of radiocarbon dates and the relative ease with which these can be processed within a so-called dates as data methodology has undoubtedly contributed to its popularity. Several limitations and forms of criticism has been directed at the approach. Some of these are of a methodological nature, while others pertain to the underlying logic. What appears to be agreed upon by practitioners and critics alike is that radiocarbon dates are best utilised in this way when compared and contrasted to other proxies for past population dynamics and other variables that might impact these [@french]. This paper reports on and attempts to unpick the relationship between two measures that have been linked to relative population sizes in the context of the Mesolithic Skagerrak coast in south-eastern Norway, namely summed radiocarbon and site frequency as evidenced by shoreline dating.

Large parts of the post-glacial landscape of Northern Scandinavia is characterised by dramatic isostatic uplift that has led to a net sea-level fall throughout the Holocene, despite eustatic sea-level rise. As coastal foragers appear to have predominantly settled on or close to the shoreline, this can be utilised to assign an approximate date to the sites, based on their present-day altitude above sea-level---a method known as shoreline dating. In a recent study, @roalkvam2023 has presented a formalised method for shoreline dating which takes into account the likely elevation of the sites above the shoreline when they were in use. This thus provides a absolute dating method with an associated probability distribution.

However, the shoreline dating of sites will reflect site frequency over time, which can also be affected by variables other than population size. In hunter-gatherer research, one of the most important of these is mobility strategies and settlement patterns. Drawing on , @roalkvam2022 demonstrated that the relationship between the volumetric density and the proportion of secondarily worked lithics in the artefact inventories of the sites appears to capture the main characteristics of their associated land-use and mobility patterns. This relationship, here instantiated as a 'curation index', is therefore included in an attempt to control for mobility patterns in the analysis.

The title of this paper includes the word 'inductive' to indicate that while some speculative thoughts concerning the relationship between the three above-outlined variables underlie the analysis, these could not be instantiated as concrete hypotheses. The data has thus been explored (or even dredged), using a wide range of techniques. As the Skagerrak coast


# Background


dates as data approach for modelling population dynamics. However, to what degree the radiocarbon record is determined by past population dynamics is not entirely clear, and might vary both geographically and chronologically, based on variation in investigatory factors as well as cultural processes within prehistoric populations. One example of the latter is the difference that can be expected between farmer and forager populations, where have suggested that an increased per capita energy consumption introduced with farming means that a single ^14^C-date should not be weighted equally when making relative population estimates across such populations.

The dates-as-data approach is dependent on there being a direct link between the past generation of material that ultimately become ^14^C samples and population size. The sum of shoreline dated sites, on the other hand, is instead determined by site frequency, and if used as a proxy for population size is therefore dependent on there being a connection between site count and population size. If a comparison of these proxies do not match it is thus an open question what factors have impacted either distribution to cause this discrepancy, and which measure, if any, directly reflect true population dynamics. 

 whether this is the result of factors that impact these measures differently

For example @timpson2021 put this well: 'the SPD is not *the* single best explanation of the data, nor even *a* explanation of the data, but rather a conflation of many possible explanations simultaneously, each of which is mired by the artefacts inherited from the calibration wiggles.' The SPD is not a model. It is the combined representation of a range of possible explanations for the data---the frequency of dated events combined with the variable uncertainty associated with these. This means that an SPD cannot be used directly to draw inferences on population dynamics, nor can it be directly compared to other time-series data. 

RSPDs in Norway have most commonly been used within a null-hypothesis significance testing approach by means of Monte Carlo simulation, as introduced by [@shennan2013]. This works by comparing the observed RSPD with a series of simulated RSPDs generated from a null-model. These null-models are typically a uniform model and/or a exponential or logistic model, fit to the observed RSPD by means of direct regression. The result from these simulations are then used to create a 95% critical envelope representing the null-model. The proportion of the observed RSPD that falls outside this envelope is then used to estimate a p-value indicating whether the null-model can be rejected. In the case that it can, the portions of the observed RSPD that falls outside this envelope can subsequently be interpreted as representing potentially meaningful demographic events, relative to the null-model. However, care has to be taken in how these should be interpreted and a degree of inferential modesty. Apart from the fundamental, this follows from. First of all, the null model

After rejecting the null of either uniform or one exponential model growth rate, that is to say, after concluding that these models do not describe the underlying population dynamics, one then goes on to interpret the deviances from these null models as indications of population boom and busts. However, 

# Methods and data

Radiocarbon dates were retrieved from. Dates done on food crusts were excluded due to the marine reservoir effect [@nilesen2021]. The dates for each site were then binned in 200-year bins to reduce the impact of.  

Sites surveyed by means of test-pitting were retrieved from the national heritage database Askeladden. A total of 1318 records were retrieved. These were then manually reviewed and given a quality score based on the criteria in Table [see @roalkvam2020]. This resulted in 1310 sites in total. 

While excavated volume is generally reported, there are some instances where this is not as clearly presented and had to be estimated based on descriptions of the excavation [e.g. @reitan2019]. These estimates might be slightly off, but are not considered to be of

To illustrate the technique, an example shoreline date is provided in figure. Unlike previous applications which have simply summed the point estimates of shoreline dated sites within arbitrary bins of 100, 200 or 500 years, the approach taken here aims to take account of the uncertainty in the trajectory of sea-level change and the uncertainty in the distance between the sites and their contemporaneous shoreline. 

In much the same way as characteristics of the calibration curve can introduce bias to the SPD, the same is true for the summed shoreline dates. To account for this, previous studies have simulated a based on some defined null model. A similar approach is adopted here, with some important adjustments to meet the idiosyncrasies of shoreline dating. First of all the shoreline displacement curves are interpolated to each site location based on its location along a south-west--north-east gradient, meaning that each site is effectively associated with a unique shoreline displacement curve. With the analogy to the radiocarbon methodology, this would be equivalent to each date being associated with a unique calibration curve. As it would not have been computationally tractable to interpolate a shoreline displacement curve to each simulated shoreline date, we instead interpolated a displacement curve to the centre of every 2.5km interval along the gradient. These in total 87 intervals were then assigned a probability weight based on how the density of sites 

As the computational cost of interpolating the shoreline displacement trajectory to each simulated location would be too high, one shoreline displacement curve was initially interpolated to the centre of each of a series of 2.5km intervals running perpendicular to the gradient in sea-level fall between the extremes of the distribution of sites. These in total 87 intervals were then assigned a probability weight based on how the density of observed sites is distributed among them.  

A sample of calendar dates are drawn from the observed date range in the SSPD, where the probability of drawing any individual year is determined by the null-model of choice. Each sampled date is then assigned one of the 87 displacement curves, the probability of which is weighted by the density of observed sites within each 2.5km interval. The calendar date is then "back-calibrated"---to follow the SPD terminology---to an elevation range from which a single elevation value is then drawn with a uniform probability, using intervals of 5km. This elevation value is then shoreline dated using the displacement curve for the relevant 2.5km interval and the default decay ratio of. 

These in total 87 intervals were then assigned a probability weight based on how the density of observed sites is distributed among them. 

Following @crema2021, the null model is  This is very much analogous to how previous studies have employed Monte Carlo simulation to take into account the nature of the calibration curve when conducting palaeodemographic modelling using radiocarbon dates. However, in this case it is not only the spatially contingent variability in sea-level change that dictates how the simulation should be perfomed, but also the fact that not only the velocity but also the physical setting might introduce a bias in the estimates. Thus, to perform a comparable simulation, the Monte Carlo-generated envelope that is employed here is based on generating random points in the landscape under study. This done both to take account of the variable trajectory of sea-level change and the potentially variable altitudinal characteristics of the landscape. If some altitudes are more common than others, what might e observed when simply might be a reflection of the characteristics of the landscape, and not a demographic signal.  

Given that the shoreline displacement curves have a uniform uncertainty range between a upper and a lower limit, flat parts of the displacement curve does not lead to the issue of infinite intercepts that characterises the calibration of radiocarbon dates [see @weninger]. Normalisating the shoreline dates to to sum to unity will therefore not create spurious spikes in the SPD as the probability of the shoreline dates will never sum to more than one [cf. @crema2022; @weninger2009]. 

To generate a critical envelope from the 

The curation index is based on. Sites which have signifcant typological indicators from multiple phases have therefore been excluded. Sites which are typologically unified, but where radiocarbon dates suggest multiple settlement phases. 


# Results

# Discussion

# Conclusion

<!-- The following line inserts a page break  -->

\newpage

# References 

<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->

<div id="refs"></div>

